apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sumeet27/kub-demo-frontend:latest
          # env:
          #   - name: AUTH_ADDRESS
          #     # value: "10.99.104.252"
          #     value: "auth-service.default"
          #   - name: TASKS_FOLDER
          #     value: tasks