import { useMemo } from "react";
import { Equal, Expect } from "../helpers/type-utils";

export const Component = () => {
  /**
   * you type the return type manually, which, as we've seen, makes sure that you're passing the specific 
   *  thing or you're typing the exact thing that's it's returning because, just like in useState, you might
   *  get some excess property check errors if you don't do this.
   */
  const autoGeneratedIds = useMemo((): string[] => {
    // generate 100 random string uuid's
    return Array.from({ length: 100 }, () =>
      Math.random().toString(36).substr(2, 9)
    );
  }, []);

  type test = Expect<Equal<typeof autoGeneratedIds, string[]>>;
};
