import { useMemo } from "react";
import { Equal, Expect } from "../helpers/type-utils";

export const Component = () => {
  /**
   * Here we manually give generioc type a value.This might be useful if you have a function where it can return 
   * lots of different things or your function has many branches and you want to make sure that it's locked down
   * what it's returning.
   * 
   * here if your function does not return string type then you will get error
   */
  const autoGeneratedIds = useMemo<string[]>(() => {
    // generate 100 random string uuid's
    return Array.from({ length: 100 }, () =>
      Math.random().toString(36).substr(2, 9)
    );
  }, []);

  type test = Expect<Equal<typeof autoGeneratedIds, string[]>>;
};
