apiVersion: v1
kind: ConfigMap
metadata:
  name: data-store-env
data:
  # here we define environment variables that will be used in the container
  folder: story
  log_level: INFO
  # key:value, here we can also use multiline string when we wnt to consume configMap as volume
  # when used as volume each property will corrpospond to file in volume
  application.properties: |
    app.name=MyAwesomeApp
    app.version=1.0.0
    server.port=8080
    # ... more properties