# Doc LInk - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
# Search kubernetes deployment yaml to see latest version
apiVersion: apps/v1
# kind of kubernetes object that you would like to create.value can be only supported kubernetes objects
# you can check API refrence of kubernetes to see all supported objects and configurations - kubernetes docs -> refrence-> api refrence, then
#   search required object like deployment. you can see all config that this object supports
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
kind: Deployment
# See docs , which other values can be added in metadata section.metadata is not applicable for all objects but for many it is
# althrough most options are relevent in most of cases
metadata:
  # Name of deployment
  name: second-app-deployment
  # Labels are used to select a resource by other resource like deployment selects pod, service selects pod.
  # We can also use labels to select object while running command. for example - kubectl delete deployments,services -l group=example
  labels:
    group: example
# the specification of this deployment.And that's the meat of this object because here, we will define how this deployment
# should be configured.(DeploymentSpec)
spec:
  # No of pod instances.we can either start deployment with extra replicas or later we can scale it based on some matrix.
  # value of one, or two, or three, or even zero if you initially don't want any pods to be launched.
  replicas: 1
  # We can select by labels only, we cannot use name . here
  selector:
    # key-value pair of pod labels that we want to match with this deployment. we already define which pods should be created by this deployment, so why we need selectors?
    # pods defined in this deployment will be created when deployment is applied. but deployment is dynamic things in kubernetes.For example,if you scale up the number of pods
    # after a deployment has been created,these new pods which are created will still automatically be managed by the already existing deployment.
    
    # so a deployment continuously watches all the pods which are out there and sees if there are any pods it should control.And it selects the to be controlled pods with a
    # so-called selector.Now there are different types of selectors here for a deployment we can use two different kinds of selecting -
    #   matchLabels - you simply have key/value pairs of labels on the pods which should be controlled by that deployment.see template section deployment object.
    #   matchExpressions - more complex so for now we will look at only matchLabels.
    # you will see selectors on pretty much all resources Kubernetes works with.For example, Also Services.
    matchLabels:
      #     # both of these lables with exact same values needs to be in pod, which will be manged by this deployment
      # Note - deployment always needs to select the pods that it creates.
      app: second-app
      tier: backend
    # this is matchExpressions syntax. here we have expressions and all of these needs to be satified in order for a pod to be selected by this deployment.
    # Supported operators - In, NotIn, Exists and DoesNotExist
    # matchExpressions:
    #   - {key: app, operator: In , values : [second-app]}

  # Here You will define the pods that should be created as part of this deployment. PodTemplateSpec
  template:
    # since template defines pod which is another kubernetes object, so we add metadata.
    # we do not need kind here because template always describes the pod.you can optionally give name also in metadata
    metadata:
      # we can give it name but here we give it label.
      #any key value pair is acceptable.You can have one or more labels on a given object in this case on a pod.
      # And then you can connect that to another object in this case, to the deployment with a so-called selector
      labels:
        app: second-app
        tier: backend
    # (PodSpec) - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
    # This is the specification of individual pod that should be created for deployment.we can only have one type of pod in a deployment
    #   we can different replicas of same pod type. but in on deployment there can be one pod type. if you have multiple pods types
    #   i.e different pods with different containers, then you need to create different deployment objects.
    spec:
      # here we have multiple containers so we need to have '-'
      # this is like docker-compose, you can specify large list of options for each container, like you cn specify when
      # manually starting container, entryPoint etc
      # docs - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container
      containers:
        - name: second-node
          # image: kub-first-app:1.0.0
          image: sumeet27/kub-first-app:2
          # This not speciffied this default to always ,if image tag is :latest
          # if explicitly defined - always, then it will always pull the image even if no tag is present
          # otherValues - Never, IfNotPresent
          # Note - even with Always value kubernetes will only fetch the image when it sees a chnage in desired state.
          # If you just update the tag and nothing in deployment, then image will not be pulled.
          # use - kubectl rollout restart deployment/"deloymentName" , in such cases
          imagePullPolicy: Always
          # This how Kubernetes checks whether your pods and containers,whether they are healthy or not,
          livenessProbe: 
            httpGet:
              path: /
              port: 8080
            #   httpHeaders:
            #     - name: X-My-Header
            #       value: my-value
            # after how much time health should be checked
            periodSeconds: 10
            #  How much time it should wait to check health first time
            initialDelaySeconds: 5
                    # here we make volume avalible to container
          # volume with this name needs to be defined in volume section
          volumeMounts:
              # This is container's internal path
            - mountPath: /app/story
            # here we define volume we are using for this path.
            # This volume name should match the name defined in volumes section i.e this volume should be avalible in pod
              name: story-volume
          env:

            # Option 1 - Specifying env variables here (name - name of envVariable)
            # - name: STRORY_FOLDER
            #   value: "story"

            # Option 2 - Taking env from configMap object (only 1 option is allowed)
            # name of env variable
            - name: STORY_FOLDER
              valueFrom:
                # here we point to specififc configMap
                configMapKeyRef:
                  # name of configMap object which we want to use
                  name: data-store-env
                  # key whose value should be assigned to environmentVariable, this is defined in configMap
                  key: folder
        # - name: third-node
        #   image:
      # Since volumes are linked to Pod,so we define them at place we define and configure pod.we define them inside PodSpec
      # These are list volumes in this pod ,all containers inside this pod can use these volume
      # each volume need to have a name and then type of volume
      volumes:
        - name: story-volume
          # This is volume type. depending upon which type we chose we have more options which we can set.
          # here we want to use default setting so we use {}.
          # emptyDir simply creates a new empty directory whenever the pod starts.And it keeps this directory
          # alive and filled with data as long as the pod is alive.Containers can then write 
          # to this directory.And if containers restart or are removed,the data survives.But if the pod should be removed,
          # this directory is removed.
          # then when pod restarts an emoty volume is created
          # point to be noted - data is stored inn pod.
          
          # emptyDir: {}
          
          # here data is stored to stored on host machine, not on pod.It is somewhat like bindMount, you can also share some data 
          # that exists on machine with pod
          #   path - path on host ,machine where data will be stored this path here is generally up to you,you just shouldn't use 
          #       any paths which are reserved in Linux,
          #   type - Now we just also need to provide a type where we let Kubernetes know how this path should be handled.
          #     DirectoryOrCreate - create this path of it does not exists yet(/data)
          #     Directory - it will fail if the directory does not exists
          
          #   hostPath:
          #     path: /data
          #     type: DirectoryOrCreate


          # here we use persistent volume
          persistentVolumeClaim:
            # this is name of PvcClaim object that we want to use
            claimName: host-pvc
        - name: config-volume
          configMap:
            name: my-app-config # Name of the ConfigMap to mount
            # The items field allows you to selectively mount specific keys from the ConfigMap and even rename the files as 
            # they appear in the container. This is useful if you only need a subset of the ConfigMap data or if the file 
            # names need to match specific conventions for your application.
            # optional: 
            # items: # You can specify which keys to mount as files
            #   - key: log_level
            #     path: logging.conf # Mounts 'log_level' as 'logging.conf'
            #   - key: application.properties
            #     path: app.properties # Mounts 'application.properties' as 'app.properties'
            # defaultMode: 0644 # Optional: set file permissions (octal)
