apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  # Template for pod - PodTemplateSpec. Deployment can manage only 1 kind of pod
  template:
    metadata:
      labels:
        app: users
    # PodSpec - Specification of the desired behavior of the pod.
    spec: 
      containers:
        - name: users
          # On using latest tag kubernetes always refetches and reevaluate the image, when something changes about deployment config
          image: sumeet27/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # here we access the clusterIP of service by - kubectl get services
              # value: 10.106.37.75
              # Internal DNS creates a url for reaching to service - `{serviceName}.{namespaceName}`. these are internal to cluster
              # If you do not give any namescapec while creating service, then it is 'default'
              value: "auth-service.default"


