apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
# these 3 dashes means that a brand new yaml object starts thereafter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # All These expressions needs to be satisfied for a pod to be included in deployment
    # we have different types of operators. this is just for demonsration, here we do need this complicated selector
    # matchExpressions:
    #   - {key: app, operator: In , values : [second-app]}
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: sumeet27/kub-first-app:2
