apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  # A selector identifies which other resources should be controlled or connected to this resource.
    # In this case here, we wanna define which pods should be part of this service.

  # Now this eslector of the service object works a bit differently than the one from the deployment object.There, we had matchlabels
    # and then our label key value pairs,which we wanted to connect.Now, we had this syntax here because the deployment resource type is a bit newer.
    # than service resource type. so selector for service is simpler. here you can match only labels, so matchLabels is no required.
  selector:
    app: second-app
  # You can expose more than one port
  ports:
    # default is TCP only
    - protocol: 'TCP'
      port: 80
      # this is port inside container
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer